---
title: "demo"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

## Generate dataset


```{r}
source("data generation.R")
# set the path for saving dataset
root.dir <- "C:/Python_R/aistat_code/simulation data"
# the setting for bridge function h
settings = c("linear_1") # or "linear_2", "nonlinear_1", "nonlinear_2"
sample.sizes = c(400) 
seeds = c(100)
# seeds = c(seq(100,896,4))
n.seeds = length(seeds)

grid <- expand.grid(settings,sample.sizes)

for (k in 1:nrow(grid)){
  
  setup <- grid[k,]
  sim.setting <- setup[[1]]; n.sample=setup[[2]]
  
  setup <- paste0(sim.setting, "_size", n.sample)
  dir.create(file.path(root.dir, setup), recursive = TRUE)
  
  for (i in 1:n.seeds){
    seed <- seeds[i]
    generation_PMMR(seed, n.sample=n.sample, setting=sim.setting)
  }
}

```

## Run the proposed method



```{python}
from pmmr_crossfit import *

sname = "linear_1_size400"
data_seeds = [100]

ROOT_PATH = "C:/Python_R/aistat_code" # the directory where you have the folder "simulation data"

# set up the parameters
log_al_bounds, log_bl_bounds = np.array([-1.5, 1.5]), np.array([-4., 2.])
args = parameters(sem="sim", hparam="lmo", selection_metric="mmr_v", cond_metric=False,
              supp_test=False, log_al_bounds=log_al_bounds, log_bl_bounds=log_bl_bounds, 
              nystr_M=nystr_M, offset=False, lmo="bl")



pmmr = run_pmmr_rkhs(seed=seed, al_diff_search_range=al_diff_search_range, bl_search_range=bl_search_range,  
        train_sizes=train_sizes, data_seeds=data_seeds, sname=sname, args=args)
mse = np.array(pmmr)[:,0]

```

```{python}
from pmmr_no_crossfit import *

sname = "linear_1_size400"
data_seeds = [100]

ROOT_PATH = "C:/Python_R/aistat_code" # the directory where you have the folder "simulation data"

# set up the parameters
log_al_bounds, log_bl_bounds = np.array([-1.5, 1.5]), np.array([-4., 2.])
args = parameters(sem="sim", hparam="lmo", selection_metric="mmr_v", cond_metric=False,
              supp_test=False, log_al_bounds=log_al_bounds, log_bl_bounds=log_bl_bounds, 
              nystr_M=nystr_M, offset=False, lmo="bl")

pmmr_noCF = run_pmmr_rkhs_noCF(seed=seed, al_diff_search_range=al_diff_search_range,
          bl_search_range=bl_search_range, train_sizes=train_sizes, data_seeds=data_seeds, 
          sname=sname, args=args)
mse_noCF = np.array(pmmr_noCF)[:,0]

```

